import { writable } from 'svelte/store';

const storedAccessToken = localStorage.getItem('accessToken');
const storedRefreshToken = localStorage.getItem('refreshToken');

export const accessToken = writable(storedAccessToken);
export const refreshToken = writable(storedRefreshToken);

accessToken.subscribe(value => localStorage.setItem('accessToken', value || undefined))
refreshToken.subscribe(value => localStorage.setItem('refreshToken', value || undefined))

export const searchText = writable('');
export const translation = writable('ELB1905STR');
export const translation2 = writable('LUTH1912');
export const originTranslation = writable('GNTTR');
export const book = writable(40);
export const chapter = writable(0);
export const hoveredStrong = writable(0);
export const lang = writable('en');

export const chapterCount = [50, 40, 27, 36, 34, 24, 21, 4, 31, 24, 22, 25, 29, 36, 10, 13, 10, 42, 150, 31, 12, 8, 66, 52, 5, 48, 12, 14, 3, 9, 1, 4, 7, 3, 3, 3, 2, 14, 3, 28, 16, 24, 21, 28, 16, 16, 13, 6, 6, 4, 4, 5, 3, 6, 4, 3, 1, 13, 5, 5, 3, 5, 1, 1, 1, 22];
export const bookNames = {
	'de': {
		'long': ['1.Mose','2.Mose','3.Mose','4.Mose','5.Mose','Josua','Richter','Rut','1.Samuel','2.Samuel','1.Könige','2.Könige','1.Chronik','2.Chronik','Esra','Nehemia','Esther','Hiob','Psalmen','Sprüche','Prediger','Hohelied','Jesaja','Jeremia','Klagelieder','Hesekiel','Daniel','Hosea','Joel','Amos','Obadja','Jona','Micha','Nahum','Habakuk','Zefanja','Haggai','Sacharja','Maleachi','Matthäus','Markus','Lukas','Johannes','Apgostelgeschichte','Römer','1.Korinther','2.Korinther','Galater','Epheser','Philliper','Kolosser','1.Thessalonicher','2.Thessalonicher','1.Timotheus','2.Timotheus','Titus','Philemon','Hebräer','Jakobus','1.Petrus','2.Petrus','1.Johannes','2.Johannes','3.Johannes','Judas','Offenbarung'],
		'short': ['1Mos','2Mos','3Mos','4Mos','5Mos','Jos','Ri','Rut','1Sam','2Sam','1Kön','2Kön','1Chr','2Chr','Esra','Neh','Est','Hi','Ps','Spr','Pred','Hld','Jes','Jer','Klgl','Hes','Dan','Hos','Joel','Am','Obd','Jon','Mi','Nah','Hab','Zef','Hag','Sach','Mal','Mt','Mk','Lk','Joh','Apg','Röm','1Kor','2Kor','Gal','Eph','Phil','Kol','1Thess','2Thess','1Tim','2Tim','Tit','Phlm','Heb','Jak','1Pet','2Pet','1Joh','2Joh','3Joh','Jud','Offb'],
		'search': [",1.Mose,1Mos,Genesis,Gen,1Mo,1.Mo,1.Mos,Mo,Mos,Mose1,",
			",2.Mose,2Mos,Exodus,Ex,2Mo,2.Mo,2.Mos,",
			",3.Mose,3Mos,Levitikus,Lev,3Mo,3.Mo,3.Mos,",
			",4.Mose,4Mos,Numeri,Num,4Mo,4.Mo,4.Mos,",
			",5.Mose,5Mos,Deuteronomium,Dtn,5Mo,5.Mo,5.Mos,",
			",Josua,Jos,",
			",Richter,Ri,",
			",Rut,Rut,",
			",1.Samuel,1Sam,1.Sam,Sam,Samuel,",
			",2.Samuel,2Sam,2.Sam,",
			",1.Könige,1Kön,1Kö,1.Kö,1.Kön,Kö,Kön,Könige,",
			",2.Könige,2Kön,2Kö,2.Kö,2.Kön,",
			",1.Chronik,1Chr,1.Chr,Chr,Chronik,",
			",2.Chronik,2Chr,2.Chr,",
			",Esra,Esra,",
			",Nehemia,Neh,",
			",Esther,Ester,Est,",
			",Hiob,Hi,Ijob,Job,",
			",Psalmen,Ps,",
			",Sprüche,Spr,",
			",Prediger,Pred,Kohelet,Koh,",
			",Hoheslied,Hld,Hohes Lied,",
			",Jesaja,Jes,",
			",Jeremia,Jer,",
			",Klagelieder,Klgl,Klag,",
			",Hesekiel,Hes,Ezechiel,Ez,",
			",Daniel,Dan,",
			",Hosea,Hos,",
			",Joel,Joel,",
			",Amos,Am,",
			",Obadja,Obd,",
			",Jona,Jona,",
			",Micha,Mi,",
			",Nahum,Nah,",
			",Habakuk,Hab,",
			",Zefanja,Zef,",
			",Haggai,Hag,",
			",Sacharja,Sach,",
			",Maleachi,Mal,",
			",Matthäus,Mt,",
			",Markus,Mk,",
			",Lukas,Lk,",
			",Johannes,Joh,",
			",Apostelgeschichte,Apg,",
			",Römer,Röm,",
			",1.Korinther,1Kor,1.Kor,Kor,Korinther,",
			",2.Korinther,2Kor,2.Kor,",
			",Galater,Gal,",
			",Epheser,Eph,",
			",Philipper,Phil,",
			",Kolosser,Kol,",
			",1.Thessalonicher,1Thess,1.Thess,Thess,Thessalonicher,1.Th,1Th,",
			",2.Thessalonicher,2Thess,2.Thess,2Th,2.Th,",
			",1.Timotheus,1Tim,Timotheus,1.Tim,",
			",2.Timotheus,2Tim,2.Tim,",
			",Titus,Tit,",
			",Philemon,Phlm,",
			",Hebräer,Hebr,Heb,",
			",Jakobus,Jak,",
			",1.Petrus,1Petr,1.Petr,1.Pet,1.Pe,1Pet,1Pe,Pe,Pet,Petr,Petrus,",
			",2.Petrus,2Petr,2.Petr,2.Pet,2.Pe,2Pet,2Pe,",
			",1.Johannes,1Joh,1.Joh,1Jo,",
			",2.Johannes,2Joh,2.Joh,2Jo,",
			",3.Johannes,3Joh,3.Joh,3Jo,",
			",Judas,Jud,",
			",Offenbarung,Offb,"],
	},
	'en': {
		'long': ['1.Mose','2.Mose','3.Mose','4.Mose','5.Mose','Josua','Richter','Rut','1.Samuel','2.Samuel','1.Könige','2.Könige','1.Chronik','2.Chronik','Esra','Nehemia','Esther','Hiob','Psalmen','Sprüche','Prediger','Hohelied','Jesaja','Jeremia','Klagelieder','Hesekiel','Daniel','Hosea','Joel','Amos','Obadja','Jona','Micha','Nahum','Habakuk','Zefanja','Haggai','Sacharja','Maleachi','Matthäus','Markus','Lukas','Johannes','Apgostelgeschichte','Römer','1.Korinther','2.Korinther','Galater','Epheser','Philliper','Kolosser','1.Thessalonicher','2.Thessalonicher','1.Timotheus','2.Timotheus','Titus','Philemon','Hebräer','Jakobus','1.Petrus','2.Petrus','1.Johannes','2.Johannes','3.Johannes','Judas','Offenbarung'],
		'short': ['1Mos','2Mos','3Mos','4Mos','5Mos','Jos','Ri','Rut','1Sam','2Sam','1Kön','2Kön','1Chr','2Chr','Esra','Neh','Est','Hi','Ps','Spr','Pred','Hld','Jes','Jer','Klgl','Hes','Dan','Hos','Joel','Am','Obd','Jon','Mi','Nah','Hab','Zef','Hag','Sach','Mal','Mt','Mk','Lk','Joh','Apg','Röm','1Kor','2Kor','Gal','Eph','Phil','Kol','1Thess','2Thess','1Tim','2Tim','Tit','Phlm','Heb','Jak','1Pet','2Pet','1Joh','2Joh','3Joh','Jud','Offb'],
		'search': [",1.Mose,1Mos,Genesis,Gen,1Mo,1.Mo,1.Mos,Mo,Mos,Mose,",
			",2Mose,2Mos,Exodus,Ex,2Mo,2.Mo,2.Mos,",
			",3Mose,3Mos,Levitikus,Lev,3Mo,3.Mo,3.Mos,",
			",4Mose,4Mos,Numeri,Num,4Mo,4.Mo,4.Mos,",
			",5Mose,5Mos,Deuteronomium,Dtn,5Mo,5.Mo,5.Mos,",
			",Josua,Jos,",
			",Richter,Ri,",
			",Rut,Rut,",
			",1Samuel,1Sam,1.Sam,Sam,Samuel,",
			",2Samuel,2Sam,2.Sam,",
			",1Könige,1Kön,1Kö,1.Kö,1.Kön,Kö,Kön,Könige,",
			",2Könige,2Kön,2Kö,2.Kö,2.Kön,",
			",1Chronik,1Chr,1.Chr,Chr,Chronik,",
			",2Chronik,2Chr,2.Chr,",
			",Esra,Esra,",
			",Nehemia,Neh,",
			",Esther,Ester,Est,",
			",Hiob,Hi,Ijob,Job,",
			",Psalmen,Ps,",
			",Sprüche,Spr,",
			",Prediger,Pred,Kohelet,Koh,",
			",Hoheslied,Hld,Hohes Lied,",
			",Jesaja,Jes,",
			",Jeremia,Jer,",
			",Klagelieder,Klgl,Klag,",
			",Hesekiel,Hes,Ezechiel,Ez,",
			",Daniel,Dan,",
			",Hosea,Hos,",
			",Joel,Joel,",
			",Amos,Am,",
			",Obadja,Obd,",
			",Jona,Jona,",
			",Micha,Mi,",
			",Nahum,Nah,",
			",Habakuk,Hab,",
			",Zefanja,Zef,",
			",Haggai,Hag,",
			",Sacharja,Sach,",
			",Maleachi,Mal,",
			",Matthäus,Mt,",
			",Markus,Mk,",
			",Lukas,Lk,",
			",Johannes,Joh,",
			",Apostelgeschichte,Apg,",
			",Römer,Röm,",
			",1Korinther,1Kor,1.Kor,Kor,Korinther,",
			",2Korinther,2Kor,2.Kor,",
			",Galater,Gal,",
			",Epheser,Eph,",
			",Philipper,Phil,",
			",Kolosser,Kol,",
			",1Thessalonicher,1Thess,1.Thess,Thess,Thessalonicher,1.Th,1Th,",
			",2Thessalonicher,2Thess,2.Thess,2Th,2.Th,",
			",1Timotheus,1Tim,Timotheus,1.Tim,",
			",2Timotheus,2Tim,2.Tim,",
			",Titus,Tit,",
			",Philemon,Phlm,",
			",Hebräer,Hebr,Heb,",
			",Jakobus,Jak,",
			",1Petrus,1Petr,1.Petr,1.Pet,1.Pe,1Pet,1Pe,Pe,Pet,Petr,Petrus,",
			",2Petrus,2Petr,2.Petr,2.Pet,2.Pe,2Pet,2Pe,",
			",1Johannes,1Joh,1.Joh,1Jo,",
			",2Johannes,2Joh,2.Joh,2Jo,",
			",3Johannes,3Joh,3.Joh,3Jo,",
			",Judas,Jud,",
			",Offenbarung,Offb,"],
	}
};